title: Diego Osborn
logo: /assets/img/circ-pfp.png
description: Hey there! My name is Diego, I am a baseball geek and I study Data Science with minors in Economics and Mathematics at the University of California, San Diego.
# show_downloads: true
theme: jekyll-theme-minimal
